# Generated by Django 5.0.2 on 2024-03-18 06:52

import Jagruti.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jagruti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='level',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(upload_to=Jagruti.models.employee_image_path),
        ),
    ]
