# Generated by Django 5.0.2 on 2024-03-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jagruti', '0002_employee_level_alter_employee_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocietyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_heading', models.CharField(max_length=100)),
                ('detail_info', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5'), (6, 'Level 6'), (7, 'Level 7'), (8, 'Level 8'), (9, 'Level 9'), (10, 'Level 10'), (11, 'Level 11'), (12, 'Level 12'), (13, 'Level 13'), (14, 'Level 14')], default=1),
        ),
    ]
