# Generated by Django 5.0.2 on 2024-03-18 10:20

import Jagruti.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jagruti', '0003_societyinformation_alter_employee_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=Jagruti.models.file_upload_path)),
            ],
        ),
    ]
